version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/codecondb
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codecondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111111
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
